-- NGX investment platform schema. Run once on an empty MySQL 8+ database.
CREATE DATABASE IF NOT EXISTS ngx_invest CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ngx_invest;

CREATE TABLE roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE, description VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE role_permissions (role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id), FOREIGN KEY(permission_id) REFERENCES permissions(id)) ENGINE=InnoDB;
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role_id BIGINT UNSIGNED NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, phone VARCHAR(32) UNIQUE, password_hash VARCHAR(255) NOT NULL, status ENUM('pending_email','active','suspended','closed') NOT NULL DEFAULT 'pending_email', kyc_status ENUM('not_started','pending','verified','rejected','review_required') NOT NULL DEFAULT 'not_started', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id), KEY(status), KEY(kyc_status)) ENGINE=InnoDB;
CREATE TABLE email_verifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, verified_at DATETIME, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), KEY(user_id,expires_at)) ENGINE=InnoDB;
CREATE TABLE password_resets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, used_at DATETIME, FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE two_factor_auth (user_id BIGINT UNSIGNED PRIMARY KEY, secret_ciphertext VARBINARY(1024) NOT NULL, enabled_at DATETIME NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE two_factor_recovery_codes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, code_hash VARCHAR(255) NOT NULL, used_at DATETIME, FOREIGN KEY(user_id) REFERENCES users(id), KEY(user_id,used_at)) ENGINE=InnoDB;
CREATE TABLE user_sessions (id CHAR(64) PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, ip_address VARBINARY(16), user_agent VARCHAR(255), last_seen_at DATETIME NOT NULL, revoked_at DATETIME, FOREIGN KEY(user_id) REFERENCES users(id), KEY(user_id,last_seen_at)) ENGINE=InnoDB;
CREATE TABLE rate_limits (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, rate_key CHAR(64) NOT NULL UNIQUE, attempts INT UNSIGNED NOT NULL, window_started_at DATETIME NOT NULL) ENGINE=InnoDB;
CREATE TABLE security_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED, event_type VARCHAR(80) NOT NULL, metadata JSON, ip_address VARBINARY(16), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), KEY(user_id,created_at)) ENGINE=InnoDB;

CREATE TABLE assets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, symbol VARCHAR(32) NOT NULL, company_name VARCHAR(255) NOT NULL, logo_url VARCHAR(500), exchange VARCHAR(30) NOT NULL DEFAULT 'NGX', sector VARCHAR(100), industry VARCHAR(100), currency CHAR(3) NOT NULL DEFAULT 'NGN', is_active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE KEY(symbol,exchange), KEY(sector)) ENGINE=InnoDB;
CREATE TABLE market_quotes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, asset_id BIGINT UNSIGNED, symbol VARCHAR(32) NOT NULL, company_name VARCHAR(255), last_price DECIMAL(20,4), previous_close DECIMAL(20,4), change_amount DECIMAL(20,4), change_percent DECIMAL(12,6), volume BIGINT UNSIGNED, value DECIMAL(20,2), observed_at DATETIME NOT NULL, data_status ENUM('LIVE','DELAYED','END_OF_DAY','STALE','UNAVAILABLE') NOT NULL, source VARCHAR(100) NOT NULL, FOREIGN KEY(asset_id) REFERENCES assets(id), KEY(symbol,observed_at), KEY(observed_at)) ENGINE=InnoDB;
CREATE TABLE historical_prices (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, asset_id BIGINT UNSIGNED NOT NULL, price_date DATE NOT NULL, open_price DECIMAL(20,4), high_price DECIMAL(20,4), low_price DECIMAL(20,4), close_price DECIMAL(20,4), volume BIGINT UNSIGNED, source VARCHAR(100) NOT NULL, UNIQUE KEY(asset_id,price_date), FOREIGN KEY(asset_id) REFERENCES assets(id)) ENGINE=InnoDB;
CREATE TABLE corporate_actions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, asset_id BIGINT UNSIGNED NOT NULL, action_type ENUM('dividend','bonus','split','consolidation','rights','offer','takeover','merger','delisting','suspension','resumption') NOT NULL, announcement_date DATE, qualification_date DATE, ex_date DATE, payment_date DATE, ratio VARCHAR(50), amount DECIMAL(20,4), status VARCHAR(50) NOT NULL, source VARCHAR(255) NOT NULL, FOREIGN KEY(asset_id) REFERENCES assets(id), KEY(asset_id,ex_date)) ENGINE=InnoDB;
CREATE TABLE watchlists (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY(user_id,name), FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE watchlist_items (watchlist_id BIGINT UNSIGNED NOT NULL, asset_id BIGINT UNSIGNED NOT NULL, sort_order INT UNSIGNED NOT NULL DEFAULT 0, PRIMARY KEY(watchlist_id,asset_id), FOREIGN KEY(watchlist_id) REFERENCES watchlists(id), FOREIGN KEY(asset_id) REFERENCES assets(id)) ENGINE=InnoDB;

CREATE TABLE wallets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'NGN', available_balance DECIMAL(20,2) NOT NULL DEFAULT 0, pending_balance DECIMAL(20,2) NOT NULL DEFAULT 0, withdrawable_balance DECIMAL(20,2) NOT NULL DEFAULT 0, total_deposits DECIMAL(20,2) NOT NULL DEFAULT 0, total_withdrawals DECIMAL(20,2) NOT NULL DEFAULT 0, UNIQUE KEY(user_id,currency), FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE payment_transactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, provider VARCHAR(30) NOT NULL, provider_reference VARCHAR(150) NOT NULL UNIQUE, amount DECIMAL(20,2) NOT NULL, currency CHAR(3) NOT NULL, status ENUM('initialized','pending','completed','failed','reversed') NOT NULL, provider_payload JSON, completed_at DATETIME, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), KEY(user_id,status)) ENGINE=InnoDB;
CREATE TABLE ledger_entries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, reference VARCHAR(150) NOT NULL, user_id BIGINT UNSIGNED NOT NULL, wallet_id BIGINT UNSIGNED NOT NULL, entry_type ENUM('debit','credit') NOT NULL, amount DECIMAL(20,2) NOT NULL, currency CHAR(3) NOT NULL, status ENUM('pending','completed','reversed','failed') NOT NULL, description VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY(reference,entry_type), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(wallet_id) REFERENCES wallets(id), CHECK(amount > 0), KEY(user_id,created_at)) ENGINE=InnoDB;
CREATE TABLE webhook_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, provider VARCHAR(30) NOT NULL, event_id VARCHAR(150) NOT NULL, payload_hash CHAR(64) NOT NULL, processed_at DATETIME, received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY(provider,event_id), UNIQUE KEY(provider,payload_hash)) ENGINE=InnoDB;
CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(36) NOT NULL UNIQUE, user_id BIGINT UNSIGNED NOT NULL, asset_id BIGINT UNSIGNED NOT NULL, side ENUM('buy','sell') NOT NULL, order_type ENUM('market','limit','stop','stop_limit') NOT NULL, quantity DECIMAL(20,4) NOT NULL, limit_price DECIMAL(20,4), status ENUM('pending','submitted','accepted','partially_filled','filled','rejected','cancel_requested','cancelled','expired','failed') NOT NULL DEFAULT 'pending', broker_reference VARCHAR(150) UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(asset_id) REFERENCES assets(id), KEY(user_id,status)) ENGINE=InnoDB;
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, actor_type VARCHAR(30) NOT NULL, actor_id BIGINT UNSIGNED, action VARCHAR(100) NOT NULL, target_type VARCHAR(50), target_id VARCHAR(100), before_state JSON, after_state JSON, reason VARCHAR(255), ip_address VARCHAR(45), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, KEY(actor_id,created_at), KEY(action,created_at)) ENGINE=InnoDB;
INSERT INTO roles(name,description) VALUES ('investor','Default investor role'),('super_administrator','Full administration') ON DUPLICATE KEY UPDATE description=VALUES(description);
